# Header
menu:
  Home: /
  #My Works: /works
  About: /about
  #Tags: /tags

rss: /atom.xml

# User Info
user_name: Yoze
user_avatar: /images/avator.jpg
user_location: Mars
user_description: "[抖腿患者] [轻度强迫症] [道德败坏] [深井冰] [擅撸码] [喜看剧] [房奴]"
user_contact: xuyoze@gmail.com
user_introduction: ""

github_username: xuyoze
twitter_username: 
weibo_username:
zhihu_username: 
facebook_username:
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: MTAyMC8zMjc3Ny85MzM4

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
favicon: /favicon.ico
use_baidu_analytics: true
baidu_analytics: d484c06aa1636ad18eeb208942d6f840
google_analytics: false
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


